stages:
  - build

build-webapp:
  stage: build
  image: rustlang/rust:nightly-slim

  services:
    - docker:19.03.0-dind

  variables:
    DOCKER_HOSTNAME: docker
    DOCKER_HOST: tcp://$DOCKER_HOSTNAME:2375
    DOCKER_DRIVER: overlay2
    CARGO_HOME: $CI_PROJECT_DIR/service/.cargo
    RUST_LOG: debug

  before_script:
    - apt update
    - apt -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common
    - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
    - apt update
    - apt -y install docker-ce-cli

  script:
    - cd service
    - cargo test

  cache:
    key: cache-universe-webapp
    paths:
      - service/target
      - service/.cargo

build-webapp-container:
  stage: build
  image: docker:stable

  services:
    - docker:19.03.0-dind

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    IMAGE_TAG: $CI_REGISTRY/sazzer/universe/universe-webapp

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE_TAG:builder-$CI_COMMIT_REF_SLUG || true

  script:
    - cd service
    - docker build -t $IMAGE_TAG:builder-$CI_COMMIT_REF_SLUG --target builder --cache-from $IMAGE_TAG:builder-$CI_COMMIT_REF_SLUG .
    - docker build -t $IMAGE_TAG:latest-$CI_COMMIT_REF_SLUG --cache-from $IMAGE_TAG:builder-$CI_COMMIT_REF_SLUG .
    - docker push $IMAGE_TAG:builder-$CI_COMMIT_REF_SLUG
    - docker push $IMAGE_TAG:latest-$CI_COMMIT_REF_SLUG

