stages:
  - build
  - e2e

build-service:
  stage: build
  image: rustlang/rust:nightly-slim

  services:
    - docker:19.03.0-dind

  variables:
    DOCKER_HOSTNAME: docker
    DOCKER_HOST: tcp://$DOCKER_HOSTNAME:2375
    DOCKER_DRIVER: overlay2
    CARGO_HOME: $CI_PROJECT_DIR/service/.cargo
    RUST_LOG: debug

  before_script:
    - apt update
    - apt -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common
    - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
    - apt update
    - apt -y install docker-ce-cli

  script:
    - cd service
    - cargo test

  cache:
    key: universe-service
    paths:
      - service/target
      - service/.cargo

build-webapp:
  stage: build
  image: node:13.7.0

  before_script:
    - cd webapp
    - yarn install

  script:
    - yarn test


  cache:
    key: universe-webapp
    paths:
      - webapp/node_modules

build-service-container:
  stage: build
  image: docker:stable

  services:
    - docker:19.03.0-dind

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    IMAGE_TAG: $CI_REGISTRY/sazzer/universe/universe-service

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE_TAG:builder-$CI_COMMIT_REF_SLUG || true

  script:
    - cd service
    - docker build -t $IMAGE_TAG:builder-$CI_COMMIT_REF_SLUG --target builder --cache-from $IMAGE_TAG:builder-$CI_COMMIT_REF_SLUG .
    - docker build -t $IMAGE_TAG:latest-$CI_COMMIT_REF_SLUG --cache-from $IMAGE_TAG:builder-$CI_COMMIT_REF_SLUG .
    - docker push $IMAGE_TAG:builder-$CI_COMMIT_REF_SLUG
    - docker push $IMAGE_TAG:latest-$CI_COMMIT_REF_SLUG

build-webapp-container:
  stage: build
  image: docker:stable

  services:
    - docker:19.03.0-dind

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    IMAGE_TAG: $CI_REGISTRY/sazzer/universe/universe-webapp

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE_TAG:builder-$CI_COMMIT_REF_SLUG || true

  script:
    - cd webapp
    - docker build -t $IMAGE_TAG:builder-$CI_COMMIT_REF_SLUG --target builder --cache-from $IMAGE_TAG:builder-$CI_COMMIT_REF_SLUG .
    - docker build -t $IMAGE_TAG:latest-$CI_COMMIT_REF_SLUG --cache-from $IMAGE_TAG:builder-$CI_COMMIT_REF_SLUG .
    - docker push $IMAGE_TAG:builder-$CI_COMMIT_REF_SLUG
    - docker push $IMAGE_TAG:latest-$CI_COMMIT_REF_SLUG

build-e2e-container:
  stage: build
  image: docker:stable

  services:
    - docker:19.03.0-dind

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    IMAGE_TAG: $CI_REGISTRY/sazzer/universe/universe-e2e

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE_TAG:latest-$CI_COMMIT_REF_SLUG || true

  script:
    - cd e2e
    - docker build -t $IMAGE_TAG:latest-$CI_COMMIT_REF_SLUG --cache-from $IMAGE_TAG:latest-$CI_COMMIT_REF_SLUG .
    - docker push $IMAGE_TAG:latest-$CI_COMMIT_REF_SLUG

run-e2e:
  stage: e2e
  image: docker/compose:latest

  services: 
    - docker:19.03.0-dind

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    SERVICE_TAG: $CI_REGISTRY/sazzer/universe/universe-service
    WEBAPP_TAG: $CI_REGISTRY/sazzer/universe/universe-webapp
    E2E_TAG: $CI_REGISTRY/sazzer/universe/universe-e2e

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $SERVICE_TAG:latest-$CI_COMMIT_REF_SLUG
    - docker pull $WEBAPP_TAG:latest-$CI_COMMIT_REF_SLUG
    - docker pull $E2E_TAG:latest-$CI_COMMIT_REF_SLUG
    - docker tag $SERVICE_TAG:latest-$CI_COMMIT_REF_SLUG universe-service
    - docker tag $WEBAPP_TAG:latest-$CI_COMMIT_REF_SLUG universe-webapp
    - docker tag $E2E_TAG:latest-$CI_COMMIT_REF_SLUG universe-e2e
    - mkdir -p /universe/output

  script:
    - docker-compose -f docker-compose.e2e.yml -f docker-compose.services.yml up --exit-code-from universe-e2e-tests

  retry:
    max: 2
    when: always

  artifacts:
    name: '$CI_COMMIT_REF_SLUG-Cucumber'
    paths:
      - output/*
    when: always

