[workspace]

members = [
    "crates/entity",
    "crates/test_database_container",
    "crates/database",
    "crates/test_database_wrapper",
    "crates/templates",
    "crates/users",
    "crates/webapp"
]
