version: '3'

services:
    universe-all-postgres:
        image: postgres:11.5-alpine
        environment:
            POSTGRES_DB: universe
            POSTGRES_USER: universe
            POSTGRES_PASSWORD: universe
        networks:
            - universe-all

    universe-all-phppgadmin:
        image: dockage/phppgadmin:latest
        environment:
            - PHP_PG_ADMIN_SERVER_DESC=NuWorlds
            - PHP_PG_ADMIN_SERVER_HOST=universe-postgres
            - PHP_PG_ADMIN_SERVER_PORT=5432
            - PHP_PG_ADMIN_SERVER_SSL_MODE=disable
            - PHP_PG_ADMIN_SERVER_DEFAULT_DB=universe
            - PHP_PG_ADMIN_SHOW_ADVANCED=true
            - PHP_PG_ADMIN_SHOW_COMMENTS=true
            - PHP_PG_ADMIN_OWNED_ONLY=true
            - PHP_PG_ADMIN_SHOW_SYSTEM=true
            - PHP_PG_ADMIN_SHOW_OIDS=true
        ports:
            - "127.0.0.1:48081:80"
        depends_on:
            - universe-all-postgres
        networks:
            - universe-all

    universe-all:
        build: .
        environment:
            - PORT=8000
            - RUST_LOG=info,universe=debug
            - RUST_BACKTRACE=1
            - DATABASE_URL=postgres://universe:universe@universe-all-postgres:5432/universe
        ports:
            - "127.0.0.1:48000:8000"
        depends_on:
            - universe-all-postgres
        networks:
            - universe-all

networks:
    universe-all:
