version: '3'

services:
    universe-dev-postgres:
        image: postgres:11.5-alpine
        environment:
            POSTGRES_DB: universe
            POSTGRES_USER: universe
            POSTGRES_PASSWORD: universe
        ports:
            - "127.0.0.1:45432:5432"
        networks:
            - universe-dev

    universe-dev-phppgadmin:
        image: dockage/phppgadmin:latest
        environment:
            - PHP_PG_ADMIN_SERVER_DESC=universe
            - PHP_PG_ADMIN_SERVER_HOST=universe-dev-postgres
            - PHP_PG_ADMIN_SERVER_PORT=5432
            - PHP_PG_ADMIN_SERVER_SSL_MODE=disable
            - PHP_PG_ADMIN_SERVER_DEFAULT_DB=universe
            - PHP_PG_ADMIN_SHOW_ADVANCED=true
            - PHP_PG_ADMIN_SHOW_COMMENTS=true
            - PHP_PG_ADMIN_OWNED_ONLY=true
            - PHP_PG_ADMIN_SHOW_SYSTEM=true
            - PHP_PG_ADMIN_SHOW_OIDS=true
        ports:
            - "127.0.0.1:48081:80"
        depends_on:
            - universe-dev-postgres
        networks:
            - universe-dev

networks:
    universe-dev:
