[package]
name = "universe_entity"
version = "0.1.0"
authors = ["Graham Cox <graham@grahamcox.co.uk>"]
edition = "2018"

[dependencies]
chrono = "0.4.10"
uuid = {version = "0.8.1", features=["serde", "v4"] }

[dev-dependencies]
