[package]
name = "universe"
version = "0.1.0"
authors = ["Graham Cox <graham@grahamcox.co.uk>"]
edition = "2018"

[lib]
name = "universe"

[[bin]]
name = "universe"

[dependencies]
bcrypt = "0.6.1"
bytes = "0.5.3"
chrono = "0.4.10"
lazy_static = "1.4.0"
log = "0.4.8"
postgres = { version="0.17.0", features=["with-uuid-0_8", "with-chrono-0_4"] }
postgres-types = { version="0.1.0", features=["derive", "with-uuid-0_8", "with-chrono-0_4"] }
r2d2 = "0.8.7"
r2d2_postgres = "0.16.0"
serde = {version = "1.0.103", features=["derive"] }
uuid = {version = "0.8.1", features=["serde", "v4"] }
dotenv = "0.15.0"
glob = "0.3.0"
mockall = "0.6.0"
rocket = "0.4.2"
rocket_contrib = "0.4.2"
http = "0.2.0"
serde_json = "1.0.44"
config = "0.10.1"
tera = "1.0.1"
accept-language = "2.0.0"
fluent = "0.9.1"
unic-langid = "0.7.1"
tracing = "0.1.11"
tracing-log = "0.1.1"
tracing-subscriber = "0.1.6"

universe_database = { path = "../database" }
universe_entity = { path = "../entity" }
universe_templates = { path = "../templates" }
universe_users = { path = "../users" }

[dev-dependencies]
spectral = "0.6.0"
testcontainers = "0.8.1"
test-env-log = "0.2.0"
env_logger = "0.7.1"
insta = "0.12.0"

universe_test_database_container = { path = "../test_database_container" }
universe_test_database_wrapper = { path = "../test_database_wrapper" }
