[package]
name = "universe_users"
version = "0.1.0"
authors = ["Graham Cox <graham@grahamcox.co.uk>"]
edition = "2018"

[dependencies]
bcrypt = "0.6.1"
bytes = "0.5.3"
chrono = "0.4.10"
mockall = "0.6.0"
postgres = { version="0.17.0", features=["with-uuid-0_8", "with-chrono-0_4"] }
postgres-types = { version="0.1.0", features=["derive", "with-uuid-0_8", "with-chrono-0_4"] }
serde = {version = "1.0.103", features=["derive"] }
tracing = "0.1.11"
uuid = {version = "0.8.1", features=["serde", "v4"] }

universe_database = { path = "../database" }
universe_entity = { path = "../entity" }

[dev-dependencies]
spectral = "0.6.0"
serde_json = "1.0.44"
universe_test_database_wrapper = { path = "../test_database_wrapper" }
tracing-log = "0.1.1"
tracing-subscriber = "0.1.6"
